# Generated by Django 2.1.3 on 2018-11-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='board',
            field=models.CharField(default='wel', max_length=5),
            preserve_default=False,
        ),
    ]
